### PR TITLE
feat: active-active subscription network peering

### PR DESCRIPTION
**Pull request by bengesoff**
Need to check the tests are passing

### CODE REVIEW

**Comment by bengesoff** [comment]
First failure occurred because I changed the `AWS_TEST_CLOUD_ACCOUNT_NAME` environment variable to `R&D`, but that references a cloud account that doesn't exist. I've reset it to `2024` because that does appear to exist in the QA account

**Comment by bengesoff** [comment]
- FAIL: TestAccDataSourceRedisCloudSubscriptionPeerings_basic (896.08s)

Possibly timed out waiting for creation?

- FAIL: TestAccResourceRedisCloudActiveActiveSubscriptionDatabase_CRUDI (1134.19s)

Didn't fix the `oss_cluster_api` bug properly, have fixed now and will try again

- FAIL: TestAccResourceRedisCloudSubscriptionPeering_aws (892.56s)

- FAIL: TestAccResourceRedisCloudActiveActiveSubscriptionPeering_aws (0.11s)

**Comment by bengesoff** [comment]
> * FAIL: TestAccDataSourceRedisCloudSubscriptionPeerings_basic (896.08s)
> 
> * FAIL: TestAccResourceRedisCloudActiveActiveSubscriptionDatabase_CRUDI (1134.19s)
> 
> 
> Didn't fix the `oss_cluster_api` bug properly, have fixed now and will try again
> 
> * FAIL: TestAccResourceRedisCloudSubscriptionPeering_aws (892.56s)
> 
> 
> Possibly timed out waiting for creation?
> 
> * FAIL: TestAccResourceRedisCloudActiveActiveSubscriptionPeering_aws (0.11s)
> 
> 
> My mistake, forgot to quote a string 🤦🏻‍♂️

Update: the three peering failures seem to have been caused by the environment variables and test AWS account configuration. There was also a bit of complication caused by the API sometimes sending `vpcCidrs` as an array, and `vpcCidr` as a single string when returning the peering details. Finally the AA Database failure was caused by not fully uncommenting the `oss_cluster_api` bug checks, and then also due to an error in the Import check step. This was because the `global*` and `override_region` attributes are ignored in import and have to be manually ignored as part of the Import test.

**Comment by bengesoff** [comment]
Four failures on the last run:

- TestAccDataSourceRedisCloudSubscriptionPeerings_basic

```
Error running apply: exit status 1
        
Error: failed to create peering for subscription 152810: 400 - Bad Request: unrecognized or unexpected parameter. Invalid VPC id provided

  with rediscloud_subscription_peering.test,
  on terraform_plugin_test.tf line 39, in resource "rediscloud_subscription_peering" "test":
  39: resource "rediscloud_subscription_peering" "test" {
```

- TestAccResourceRedisCloudSubscriptionPeering_aws

```
resource_rediscloud_subscription_peering_test.go:118: *** doesn't match regex ^vpc-[a-z\d]+$
```

- TestAccResourceRedisCloudActiveActiveSubscriptionPeering_aws

```
 resource_rediscloud_subscription_peering_test.go:118: *** doesn't match regex ^vpc-[a-z\d]+$
```

- TestAccResourceRedisCloudActiveActiveSubscription_CRUDI

Subscription gave an error:

```json
{
  "id" : 152814,
  "name" : "tf-test-4358751122659340148",
  "status" : "error",
  "deploymentType" : "active-active",
  "paymentMethodId" : 16971,
  "memoryStorage" : "ram",
  "storageEncryption" : true,
  "numberOfDatabases" : 1,
  "paymentMethodType" : "credit-card",
  "cloudDetails" : [ ],
  "links" : [ {
    "rel" : "self",
    "href" : "https://api-cloudapi.qa.redislabs.com/v1/subscriptions/152814",
    "type" : "GET"
  } ]
}
```

**Review by byron-oc — APPROVED** [review]

**Pull request merged**
